CREATE TABLE afiliado_huesped (
	id_afiliado_huesped integer,
	id_afiliado integer,
	id_huesped integer
);

CREATE VIEW vista_huespedes_afiliados AS
 SELECT h.id_huesped,
    p.primer_nombre AS nombre_huesped,
    p.primer_apellido AS apellido_huesped,
    af.id_afiliado,
    af.condicion
   FROM huesped h
     JOIN persona p ON h.id_persona = p.id_persona
     LEFT JOIN afiliado_reservacion ah ON h.id_huesped = ah.id_reservacion
     LEFT JOIN afiliado af ON ah.id_afiliado = af.id_afiliado;

CREATE VIEW vista_reservacion_huesped_paciente AS
 SELECT a.id_reservacion,
    a.id_paciente_huesped,
    a.fecha_entrada,
    a.id_paciente,
    a.id_huesped,
    a.parentesco_paciente,
    a.id_hospital,
    a.observacion,
    a.id_causa_visita,
    a.id_persona_paciente,
    a.id_persona_huesped,
    a.reingreso,
    ph.primer_nombre AS primer_nombre_huesped,
    ph.segundo_nombre AS segundo_nombre_huesped,
    ph.primer_apellido AS primer_apellido_huesped,
    ph.segundo_apellido AS segundo_apellido_huesped,
    ph.telefono AS telefono_huesped,
    ph.dni AS dni_huesped,
    ph.genero AS genero_huesped,
    ph.fecha_nacimiento AS fecha_nacimiento_huesped,
    ph.id_ocupacion AS id_ocupacion_huesped,
    ph.municipio_id AS municipio_id_huesped,
    pp.primer_nombre AS primer_nombre_paciente,
    pp.segundo_nombre AS segundo_nombre_paciente,
    pp.primer_apellido AS primer_apellido_paciente,
    pp.segundo_apellido AS segundo_apellido_paciente,
    pp.telefono AS telefono_paciente,
    h.nombre AS hospital_nombre,
    c.causa AS causa_visita
   FROM ( SELECT a_1.id_reservacion,
            a_1.id_paciente_huesped,
            a_1.fecha_entrada,
            a_1.id_paciente,
            a_1.id_huesped,
            a_1.parentesco_paciente,
            p.id_hospital,
            p.observacion,
            p.id_causa_visita,
            p.id_person AS id_persona_paciente,
            h_1.id_persona AS id_persona_huesped,
            h_1.reingreso
           FROM ( SELECT r.id_reservacion,
                    r.id_paciente_huesped,
                    r.fecha_entrada,
                    ph_1.id_paciente,
                    ph_1.id_huesped,
                    ph_1.parentesco_paciente
                   FROM reservacion r
                     JOIN paciente_huesped ph_1 ON r.id_paciente_huesped = ph_1.id_paciente_huesped) a_1
             JOIN paciente p ON a_1.id_paciente = p.id_paciente
             JOIN huesped h_1 ON a_1.id_huesped = h_1.id_huesped) a
     JOIN persona pp ON a.id_persona_paciente = pp.id_persona
     JOIN persona ph ON a.id_persona_huesped = ph.id_persona
     JOIN hospital h ON a.id_hospital = h.id_hospital
     JOIN causa_visita c ON a.id_causa_visita = c.id_causa_visita;

CREATE VIEW vista_huesped_paciente_con_persona AS
 SELECT v.id_huesped,
    v.id_paciente,
    v.fecha_entrada,
    v.primer_nombre_huesped,
    v.segundo_nombre_huesped,
    v.primer_apellido_huesped,
    v.segundo_apellido_huesped,
    v.telefono_huesped,
    v.dni_huesped,
    v.genero_huesped,
    v.fecha_nacimiento_huesped,
    o.descripcion AS ocupacion_huesped,
    d.nombre AS departamento_huesped,
    m.nombre AS municipio_huesped,
    v.reingreso,
    v.primer_nombre_paciente,
    v.segundo_nombre_paciente,
    v.primer_apellido_paciente,
    v.segundo_apellido_paciente,
    v.telefono_paciente,
    v.hospital_nombre,
    v.parentesco_paciente,
    v.causa_visita,
    v.observacion
   FROM vista_reservacion_huesped_paciente v
     JOIN ocupacion o ON v.id_ocupacion_huesped = o.id_ocupacion
     JOIN municipio m ON v.municipio_id_huesped = m.municipio_id
     JOIN departamento d ON d.departamento_id = m.departamento_id;

CREATE VIEW withiglesia AS
 SELECT v.id_huesped,
    v.id_paciente,
    v.fecha_entrada,
    v.primer_nombre_huesped,
    v.segundo_nombre_huesped,
    v.primer_apellido_huesped,
    v.segundo_apellido_huesped,
    v.telefono_huesped,
    v.dni_huesped,
    v.genero_huesped,
    v.fecha_nacimiento_huesped,
    v.ocupacion_huesped,
    v.departamento_huesped,
    v.municipio_huesped,
    v.reingreso,
    i.nombre AS iglesia,
    v.primer_nombre_paciente,
    v.segundo_nombre_paciente,
    v.primer_apellido_paciente,
    v.segundo_apellido_paciente,
    v.telefono_paciente,
    v.hospital_nombre,
    v.parentesco_paciente,
    v.causa_visita,
    v.observacion
   FROM ( SELECT v_1.id_huesped,
            v_1.id_paciente,
            v_1.fecha_entrada,
            v_1.primer_nombre_huesped,
            v_1.segundo_nombre_huesped,
            v_1.primer_apellido_huesped,
            v_1.segundo_apellido_huesped,
            v_1.telefono_huesped,
            v_1.dni_huesped,
            v_1.genero_huesped,
            v_1.fecha_nacimiento_huesped,
            v_1.ocupacion_huesped,
            v_1.departamento_huesped,
            v_1.municipio_huesped,
            v_1.reingreso,
            v_1.primer_nombre_paciente,
            v_1.segundo_nombre_paciente,
            v_1.primer_apellido_paciente,
            v_1.segundo_apellido_paciente,
            v_1.telefono_paciente,
            v_1.hospital_nombre,
            v_1.parentesco_paciente,
            v_1.causa_visita,
            v_1.observacion,
            i_1.id_iglesia
           FROM vista_huesped_paciente_con_persona v_1
             LEFT JOIN iglesia_huesped i_1 ON v_1.id_huesped = i_1.id_huesped) v
     LEFT JOIN iglesia i ON v.id_iglesia = i.id_iglesia;

CREATE VIEW data_excel AS
 SELECT v.id_huesped,
    v.id_paciente,
    v.fecha_entrada,
    v.primer_nombre_huesped,
    v.segundo_nombre_huesped,
    v.primer_apellido_huesped,
    v.segundo_apellido_huesped,
    v.telefono_huesped,
    v.dni_huesped,
    v.genero_huesped,
    v.fecha_nacimiento_huesped,
    v.ocupacion_huesped,
    v.departamento_huesped,
    v.municipio_huesped,
    v.reingreso,
    v.iglesia,
    v.primer_nombre_paciente,
    v.segundo_nombre_paciente,
    v.primer_apellido_paciente,
    v.segundo_apellido_paciente,
    v.telefono_paciente,
    v.hospital_nombre,
    v.parentesco_paciente,
    v.causa_visita,
    v.observacion,
    v.nombre_afiliado,
    v.dni_afiliado,
    v.condicion_afiliado,
    p.nombre AS nombre_patrono
   FROM ( SELECT v_1.id_huesped,
            v_1.id_paciente,
            v_1.fecha_entrada,
            v_1.primer_nombre_huesped,
            v_1.segundo_nombre_huesped,
            v_1.primer_apellido_huesped,
            v_1.segundo_apellido_huesped,
            v_1.telefono_huesped,
            v_1.dni_huesped,
            v_1.genero_huesped,
            v_1.fecha_nacimiento_huesped,
            v_1.ocupacion_huesped,
            v_1.departamento_huesped,
            v_1.municipio_huesped,
            v_1.reingreso,
            v_1.iglesia,
            v_1.primer_nombre_paciente,
            v_1.segundo_nombre_paciente,
            v_1.primer_apellido_paciente,
            v_1.segundo_apellido_paciente,
            v_1.telefono_paciente,
            v_1.hospital_nombre,
            v_1.parentesco_paciente,
            v_1.causa_visita,
            v_1.observacion,
            a.nombre AS nombre_afiliado,
            a.dni AS dni_afiliado,
            a.condicion AS condicion_afiliado,
            p_1.id_patrono
           FROM ( SELECT v_2.id_huesped,
                    v_2.id_paciente,
                    v_2.fecha_entrada,
                    v_2.primer_nombre_huesped,
                    v_2.segundo_nombre_huesped,
                    v_2.primer_apellido_huesped,
                    v_2.segundo_apellido_huesped,
                    v_2.telefono_huesped,
                    v_2.dni_huesped,
                    v_2.genero_huesped,
                    v_2.fecha_nacimiento_huesped,
                    v_2.ocupacion_huesped,
                    v_2.departamento_huesped,
                    v_2.municipio_huesped,
                    v_2.reingreso,
                    v_2.iglesia,
                    v_2.primer_nombre_paciente,
                    v_2.segundo_nombre_paciente,
                    v_2.primer_apellido_paciente,
                    v_2.segundo_apellido_paciente,
                    v_2.telefono_paciente,
                    v_2.hospital_nombre,
                    v_2.parentesco_paciente,
                    v_2.causa_visita,
                    v_2.observacion,
                    a_1.id_afiliado
                   FROM withiglesia v_2
                     LEFT JOIN afiliado_huesped a_1 ON v_2.id_huesped = a_1.id_huesped) v_1
             LEFT JOIN afiliado a ON v_1.id_afiliado = a.id_afiliado
             LEFT JOIN patrono_afiliado p_1 ON v_1.id_afiliado = p_1.id_afiliado) v
     LEFT JOIN patrono p ON v.id_patrono = p.id_patrono;
